using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace RefitClassSourceGenerator;

/// <summary>
/// Incremental source generator that promotes methods from Refit interfaces to containing classes
/// </summary>
[Generator]
public class RefitClassGenerator : IIncrementalGenerator
{
	/// <summary>
	/// Registers the incremental generation pipeline that discovers eligible Refit-backed properties
	/// and emits the promoted method implementations onto their containing classes.
	/// </summary>
	/// <param name="context">The initialization context used to register the generator's providers and outputs.</param>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Find all properties with the RefitPromoteCalls attribute
		var propertiesProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is PropertyDeclarationSyntax p && p.AttributeLists.Count > 0,
				transform: static (ctx, _) => GetPropertyIfEligible(ctx))
			.Where(static p => p is not null);

		// Combine with compilation
		var compilationAndProperties = context.CompilationProvider.Combine(propertiesProvider.Collect());

		// Generate source for each property
		context.RegisterSourceOutput(compilationAndProperties, static (spc, source) => Execute(source.Left, source.Right!, spc));
	}

	private static PropertyDeclarationSyntax? GetPropertyIfEligible(GeneratorSyntaxContext context)
	{
		var propertyDeclaration = (PropertyDeclarationSyntax)context.Node;

		// Check if the property has the RefitPromoteCalls attribute
		foreach (var attributeList in propertyDeclaration.AttributeLists)
		{
			foreach (var attribute in attributeList.Attributes)
			{
				var attributeName = attribute.Name.NormalizeWhitespace().ToFullString();
				if (attributeName is "RefitPromoteCalls" or "RefitPromoteCallsAttribute")
				{
					return propertyDeclaration;
				}
			}
		}

		return null;
	}

	private static void Execute(Compilation compilation, ImmutableArray<PropertyDeclarationSyntax?> properties, SourceProductionContext context)
	{
		try
		{
			foreach (var property in properties)
			{
				if (property is not null)
				{
					GenerateForProperty(compilation, property, context);
				}
			}
		}
		catch (Exception ex)
		{
			ReportError(context, "RCG001", "Error", ex.Message);
		}
	}

	private static void GenerateForProperty(Compilation compilation, PropertyDeclarationSyntax property, SourceProductionContext context)
	{
		var semanticModel = compilation.GetSemanticModel(property.SyntaxTree);

		// Find the type of the property as this is what we want to copy properties from
		var propertyDeclaredSymbol = semanticModel.GetDeclaredSymbol(property);

		if (propertyDeclaredSymbol is null)
		{
			// Report an error message that we couldn't find the property
			ReportError(context, "RCG002", "Property Missing", $"Could not find the property {property.ToFullString()}");
			return;
		}

		var propertyInterfaceSymbol = ResolveInterface(compilation, propertyDeclaredSymbol, context);
		if (propertyInterfaceSymbol is null)
		{
			return;
		}

		// Get all the methods on the interface
		var interfaceMethodSymbols = propertyInterfaceSymbol.GetMembers().OfType<IMethodSymbol>().ToList();
		if (interfaceMethodSymbols.Count == 0)
		{
			return;
		}

		var newSource = BuildSource(propertyDeclaredSymbol, interfaceMethodSymbols);
		context.AddSource(
			$"{propertyDeclaredSymbol.ContainingType.Name}_{propertyDeclaredSymbol.Name}.g.cs",
			SourceText.From(newSource, Encoding.UTF8));
	}

	/// <summary>
	/// Finds the single interface the property's type names, reporting a diagnostic and returning
	/// null where there is not exactly one.
	/// </summary>
	private static INamedTypeSymbol? ResolveInterface(
		Compilation compilation,
		IPropertySymbol propertyDeclaredSymbol,
		SourceProductionContext context)
	{
		var propertyTypeName = propertyDeclaredSymbol.Type.ToDisplayString();
		var propertyInterfaceSymbols = GetMatchingInterfacesInSolution(compilation, propertyTypeName);

		if (propertyInterfaceSymbols.Length == 0)
		{
			// Report an error message that we couldn't find the interface
			ReportError(context, "RCG003", "Interface Missing", $"Could not find the interface {propertyTypeName}");
			return null;
		}

		if (propertyInterfaceSymbols.Length != 1)
		{
			// Report an error message that we found other than 1 interface
			ReportError(
				context,
				"RCG004",
				"Ambiguous interface reference",
				$"Found {propertyInterfaceSymbols.Length} interface symbols for {propertyTypeName}");
			return null;
		}

		return propertyInterfaceSymbols[0];
	}

	private static string BuildSource(IPropertySymbol propertyDeclaredSymbol, List<IMethodSymbol> interfaceMethodSymbols)
	{
		var sb = new StringBuilder(@$"
// <auto-generated />
namespace {propertyDeclaredSymbol.ContainingType.ContainingNamespace};

public partial class {propertyDeclaredSymbol.ContainingType.Name}
{{
");

		var processedAnyMethods = false;
		foreach (var methodSymbol in interfaceMethodSymbols)
		{
			if (processedAnyMethods)
			{
				sb.AppendLine();
			}

			if (methodSymbol.DeclaredAccessibility == Accessibility.Public)
			{
				AppendForwardingMethod(sb, propertyDeclaredSymbol, methodSymbol);
			}

			processedAnyMethods = true;
		}

		sb.AppendLine("}");
		return sb.ToString();
	}

	private static void AppendForwardingMethod(
		StringBuilder sb,
		IPropertySymbol propertyDeclaredSymbol,
		IMethodSymbol methodSymbol)
	{
		// Add XML documentation comment first
		sb.AppendLine("\t/// <inheritdoc />");

		AppendObsoleteAttribute(sb, methodSymbol);

		sb.AppendLine("\t" + methodSymbol.GetMethodSignature(true));
		var parameters = string.Join(", ", methodSymbol.Parameters.Select(p => $"{p.Name}"));
		sb.AppendLine($"\t\t=> {propertyDeclaredSymbol.Name}.{methodSymbol.Name}({parameters});");
	}

	/// <summary>
	/// Carries any Obsolete attribute, and its message, through to the generated member.
	/// </summary>
	private static void AppendObsoleteAttribute(StringBuilder sb, IMethodSymbol methodSymbol)
	{
		var obsoleteAttribute = methodSymbol.GetAttributes()
			.FirstOrDefault(a => a.AttributeClass?.Name == "ObsoleteAttribute");

		if (obsoleteAttribute is null)
		{
			return;
		}

		var obsoleteMessage = obsoleteAttribute.ConstructorArguments.Length > 0
			? obsoleteAttribute.ConstructorArguments[0].Value?.ToString()
			: null;

		sb.AppendLine(obsoleteMessage is null
			? "\t[Obsolete]"
			: $"\t[Obsolete(\"{obsoleteMessage}\")]");
	}

	private static void ReportError(SourceProductionContext context, string id, string title, string message)
		=> context.ReportDiagnostic(
			Diagnostic.Create(
				new DiagnosticDescriptor(
					id,
					title,
					message,
					"Error",
					DiagnosticSeverity.Error,
					true),
				Location.None));

	private static ImmutableArray<INamedTypeSymbol?> GetMatchingInterfacesInSolution(Compilation compilation, string name)
		=> [.. compilation.SyntaxTrees
			.SelectMany(syntaxTree =>
			{
				var semanticModel = compilation.GetSemanticModel(syntaxTree);
				return semanticModel.SyntaxTree.GetRoot()
					.DescendantNodes()
					.OfType<InterfaceDeclarationSyntax>()
					.Select(interfaceDeclarationSyntax => semanticModel.GetDeclaredSymbol(interfaceDeclarationSyntax));
			})
			.Where(symbol => symbol != null && name == symbol.ToDisplayString())];
}
