/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Meraki.Api.Data
{
	/// <summary>
	/// Band selection can be set to either 'ssid' or 'ap'. This param is required on creation.
	/// </summary>
	/// <value>Band selection can be set to either 'ssid' or 'ap'. This param is required on creation.</value>
	[JsonConverter(typeof(StringEnumConverter))]
    public enum BandSelectionType
    {

        /// <summary>
        /// Enum Ssid for "ssid"
        /// </summary>
        [EnumMember(Value = "ssid")]
        Ssid,

        /// <summary>
        /// Enum Ap for "ap"
        /// </summary>
        [EnumMember(Value = "ap")]
        Ap
    }
}
