/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Meraki.Api.Data
{
	/// <summary>
	/// Choice between 'dual', '2.4ghz' or '5ghz'.
	/// </summary>
	/// <value>Choice between 'dual', '2.4ghz' or '5ghz'.</value>
	[JsonConverter(typeof(StringEnumConverter))]
    public enum BandOperationMode1
    {

        /// <summary>
        /// Enum Dual for "dual"
        /// </summary>
        [EnumMember(Value = "dual")]
        Dual,

        /// <summary>
        /// Enum _24ghz for "2.4ghz"
        /// </summary>
        [EnumMember(Value = "2.4ghz")]
        _24ghz,

        /// <summary>
        /// Enum _5ghz for "5ghz"
        /// </summary>
        [EnumMember(Value = "5ghz")]
        _5ghz
    }
}
