/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// BindNetwork
	/// </summary>
	[DataContract]
    public partial class BindNetwork :  IEquatable<BindNetwork>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BindNetwork" /> class.
        /// </summary>
        [JsonConstructor]
        protected BindNetwork() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BindNetwork" /> class.
        /// </summary>
        /// <param name="ConfigTemplateId">The ID of the template to which the network should be bound. (required).</param>
        /// <param name="AutoBind">Optional boolean indicating whether the network&#39;s switches should automatically bind to profiles of the same model. Defaults to false if left unspecified. This option only affects switch networks and switch templates. Auto-bind is not valid unless the switch template has at least one profile and has at most one profile per switch model..</param>
        public BindNetwork(string ConfigTemplateId = default, bool? AutoBind = default)
        {
            // to ensure "ConfigTemplateId" is required (not null)
            if (ConfigTemplateId == null)
            {
                throw new InvalidDataException("ConfigTemplateId is a required property for BindNetwork and cannot be null");
            }
            else
            {
                this.ConfigTemplateId = ConfigTemplateId;
            }
            this.AutoBind = AutoBind;
        }

        /// <summary>
        /// The ID of the template to which the network should be bound.
        /// </summary>
        /// <value>The ID of the template to which the network should be bound.</value>
        [DataMember(Name="configTemplateId", EmitDefaultValue=false)]
        public string ConfigTemplateId { get; set; }
        /// <summary>
        /// Optional boolean indicating whether the network&#39;s switches should automatically bind to profiles of the same model. Defaults to false if left unspecified. This option only affects switch networks and switch templates. Auto-bind is not valid unless the switch template has at least one profile and has at most one profile per switch model.
        /// </summary>
        /// <value>Optional boolean indicating whether the network&#39;s switches should automatically bind to profiles of the same model. Defaults to false if left unspecified. This option only affects switch networks and switch templates. Auto-bind is not valid unless the switch template has at least one profile and has at most one profile per switch model.</value>
        [DataMember(Name="autoBind", EmitDefaultValue=false)]
        public bool? AutoBind { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BindNetwork {\n");
            sb.Append("  ConfigTemplateId: ").Append(ConfigTemplateId).Append("\n");
            sb.Append("  AutoBind: ").Append(AutoBind).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as BindNetwork);
        }

        /// <summary>
        /// Returns true if BindNetwork instances are equal
        /// </summary>
        /// <param name="other">Instance of BindNetwork to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BindNetwork other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  ConfigTemplateId == other.ConfigTemplateId ||
						  ConfigTemplateId != null &&
						  ConfigTemplateId.Equals(other.ConfigTemplateId)
					 ) &&
					 (
						  AutoBind == other.AutoBind ||
						  AutoBind != null &&
						  AutoBind.Equals(other.AutoBind)
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (ConfigTemplateId != null)
                    hash = hash * 59 + ConfigTemplateId.GetHashCode();
                if (AutoBind != null)
                    hash = hash * 59 + AutoBind.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
