/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// ClaimIntoOrganization
	/// </summary>
	[DataContract]
    public partial class ClaimIntoOrganization :  IEquatable<ClaimIntoOrganization>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClaimIntoOrganization" /> class.
        /// </summary>
        /// <param name="Orders">The numbers of the orders that should be claimed.</param>
        /// <param name="Serials">The serials of the devices that should be claimed.</param>
        /// <param name="Licenses">The licenses that should be claimed.</param>
        public ClaimIntoOrganization(List<string> Orders = default, List<string> Serials = default, List<License> Licenses = default)
        {
            this.Orders = Orders;
            this.Serials = Serials;
            this.Licenses = Licenses;
        }

        /// <summary>
        /// The numbers of the orders that should be claimed
        /// </summary>
        /// <value>The numbers of the orders that should be claimed</value>
        [DataMember(Name="orders", EmitDefaultValue=false)]
        public List<string> Orders { get; set; }
        /// <summary>
        /// The serials of the devices that should be claimed
        /// </summary>
        /// <value>The serials of the devices that should be claimed</value>
        [DataMember(Name="serials", EmitDefaultValue=false)]
        public List<string> Serials { get; set; }
        /// <summary>
        /// The licenses that should be claimed
        /// </summary>
        /// <value>The licenses that should be claimed</value>
        [DataMember(Name="licenses", EmitDefaultValue=false)]
        public List<License> Licenses { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClaimIntoOrganization {\n");
            sb.Append("  Orders: ").Append(Orders).Append("\n");
            sb.Append("  Serials: ").Append(Serials).Append("\n");
            sb.Append("  Licenses: ").Append(Licenses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as ClaimIntoOrganization);
        }

        /// <summary>
        /// Returns true if ClaimIntoOrganization instances are equal
        /// </summary>
        /// <param name="other">Instance of ClaimIntoOrganization to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClaimIntoOrganization other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  Orders == other.Orders ||
						  Orders != null &&
						  Orders.SequenceEqual(other.Orders)
					 ) &&
					 (
						  Serials == other.Serials ||
						  Serials != null &&
						  Serials.SequenceEqual(other.Serials)
					 ) &&
					 (
						  Licenses == other.Licenses ||
						  Licenses != null &&
						  Licenses.SequenceEqual(other.Licenses)
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Orders != null)
                    hash = hash * 59 + Orders.GetHashCode();
                if (Serials != null)
                    hash = hash * 59 + Serials.GetHashCode();
                if (Licenses != null)
                    hash = hash * 59 + Licenses.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
