/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// CreateNetworkSmBypassActivationLockAttempt
	/// </summary>
	[DataContract]
    public partial class CreateNetworkSmBypassActivationLockAttempt :  IEquatable<CreateNetworkSmBypassActivationLockAttempt>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNetworkSmBypassActivationLockAttempt" /> class.
        /// </summary>
        [JsonConstructor]
        protected CreateNetworkSmBypassActivationLockAttempt() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNetworkSmBypassActivationLockAttempt" /> class.
        /// </summary>
        /// <param name="Ids">The ids of the devices to attempt activation lock bypass. (required).</param>
        public CreateNetworkSmBypassActivationLockAttempt(List<string> Ids = default)
        {
            // to ensure "Ids" is required (not null)
            if (Ids == null)
            {
                throw new InvalidDataException("Ids is a required property for CreateNetworkSmBypassActivationLockAttempt and cannot be null");
            }
            else
            {
                this.Ids = Ids;
            }
        }

        /// <summary>
        /// The ids of the devices to attempt activation lock bypass.
        /// </summary>
        /// <value>The ids of the devices to attempt activation lock bypass.</value>
        [DataMember(Name="ids", EmitDefaultValue=false)]
        public List<string> Ids { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateNetworkSmBypassActivationLockAttempt {\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as CreateNetworkSmBypassActivationLockAttempt);
        }

        /// <summary>
        /// Returns true if CreateNetworkSmBypassActivationLockAttempt instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateNetworkSmBypassActivationLockAttempt to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateNetworkSmBypassActivationLockAttempt other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: Ids == other.Ids ||
						  (Ids != null &&
						  Ids.SequenceEqual(other.Ids));
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Ids != null)
				{
					hash = (hash * 59) + Ids.GetHashCode();
				}

				return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
