/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Meraki.Api.Data
{
	/// <summary>
	/// The appliance's handling of DHCP requests on this VLAN. One of: 'Run a DHCP server', 'Relay DHCP to another server' or 'Do not respond to DHCP requests'
	/// </summary>
	/// <value>The appliance's handling of DHCP requests on this VLAN. One of: 'Run a DHCP server', 'Relay DHCP to another server' or 'Do not respond to DHCP requests'</value>
	[JsonConverter(typeof(StringEnumConverter))]
    public enum DhcpHandling
    {

        /// <summary>
        /// Enum RunaDHCPserver for "Run a DHCP server"
        /// </summary>
        [EnumMember(Value = "Run a DHCP server")]
        RunaDHCPserver,

        /// <summary>
        /// Enum RelayDHCPtoanotherserver for "Relay DHCP to another server"
        /// </summary>
        [EnumMember(Value = "Relay DHCP to another server")]
        RelayDHCPtoanotherserver,

        /// <summary>
        /// Enum DonotrespondtoDHCPrequests for "Do not respond to DHCP requests"
        /// </summary>
        [EnumMember(Value = "Do not respond to DHCP requests")]
        DonotrespondtoDHCPrequests
    }
}
