/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Meraki.Api.Data
{
	/// <summary>
	/// Set the detection ruleset 'connectivity'/'balanced'/'security' (optional - omitting will leave current config unchanged). Default value is 'balanced' if none currently saved
	/// </summary>
	/// <value>Set the detection ruleset 'connectivity'/'balanced'/'security' (optional - omitting will leave current config unchanged). Default value is 'balanced' if none currently saved</value>
	[JsonConverter(typeof(StringEnumConverter))]
    public enum IdsRulesets
    {

        /// <summary>
        /// Enum Connectivity for "connectivity"
        /// </summary>
        [EnumMember(Value = "connectivity")]
        Connectivity,

        /// <summary>
        /// Enum Balanced for "balanced"
        /// </summary>
        [EnumMember(Value = "balanced")]
        Balanced,

        /// <summary>
        /// Enum Security for "security"
        /// </summary>
        [EnumMember(Value = "security")]
        Security
    }
}
