/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// MoveNetworkSmDevices
	/// </summary>
	[DataContract]
    public partial class MoveNetworkSmDevices :  IEquatable<MoveNetworkSmDevices>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MoveNetworkSmDevices" /> class.
        /// </summary>
        [JsonConstructor]
        protected MoveNetworkSmDevices() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MoveNetworkSmDevices" /> class.
        /// </summary>
        /// <param name="WifiMacs">The wifiMacs of the devices to be moved..</param>
        /// <param name="Ids">The ids of the devices to be moved..</param>
        /// <param name="Serials">The serials of the devices to be moved..</param>
        /// <param name="Scope">The scope (one of all, none, withAny, withAll, withoutAny, or withoutAll) and a set of tags of the devices to be moved..</param>
        /// <param name="NewNetwork">The new network to which the devices will be moved. (required).</param>
        public MoveNetworkSmDevices(string WifiMacs = default, string Ids = default, string Serials = default, string Scope = default, string NewNetwork = default)
        {
            // to ensure "NewNetwork" is required (not null)
            if (NewNetwork == null)
            {
                throw new InvalidDataException("NewNetwork is a required property for MoveNetworkSmDevices and cannot be null");
            }
            else
            {
                this.NewNetwork = NewNetwork;
            }
            this.WifiMacs = WifiMacs;
            this.Ids = Ids;
            this.Serials = Serials;
            this.Scope = Scope;
        }

        /// <summary>
        /// The wifiMacs of the devices to be moved.
        /// </summary>
        /// <value>The wifiMacs of the devices to be moved.</value>
        [DataMember(Name="wifiMacs", EmitDefaultValue=false)]
        public string WifiMacs { get; set; }
        /// <summary>
        /// The ids of the devices to be moved.
        /// </summary>
        /// <value>The ids of the devices to be moved.</value>
        [DataMember(Name="ids", EmitDefaultValue=false)]
        public string Ids { get; set; }
        /// <summary>
        /// The serials of the devices to be moved.
        /// </summary>
        /// <value>The serials of the devices to be moved.</value>
        [DataMember(Name="serials", EmitDefaultValue=false)]
        public string Serials { get; set; }
        /// <summary>
        /// The scope (one of all, none, withAny, withAll, withoutAny, or withoutAll) and a set of tags of the devices to be moved.
        /// </summary>
        /// <value>The scope (one of all, none, withAny, withAll, withoutAny, or withoutAll) and a set of tags of the devices to be moved.</value>
        [DataMember(Name="scope", EmitDefaultValue=false)]
        public string Scope { get; set; }
        /// <summary>
        /// The new network to which the devices will be moved.
        /// </summary>
        /// <value>The new network to which the devices will be moved.</value>
        [DataMember(Name="newNetwork", EmitDefaultValue=false)]
        public string NewNetwork { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MoveNetworkSmDevices {\n");
            sb.Append("  WifiMacs: ").Append(WifiMacs).Append("\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("  Serials: ").Append(Serials).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  NewNetwork: ").Append(NewNetwork).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as MoveNetworkSmDevices);
        }

        /// <summary>
        /// Returns true if MoveNetworkSmDevices instances are equal
        /// </summary>
        /// <param name="other">Instance of MoveNetworkSmDevices to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MoveNetworkSmDevices other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  WifiMacs == other.WifiMacs ||
						  (WifiMacs != null &&
						  WifiMacs.Equals(other.WifiMacs))
					 ) &&
					 (
						  Ids == other.Ids ||
						  (Ids != null &&
						  Ids.Equals(other.Ids))
					 ) &&
					 (
						  Serials == other.Serials ||
						  (Serials != null &&
						  Serials.Equals(other.Serials))
					 ) &&
					 (
						  Scope == other.Scope ||
						  (Scope != null &&
						  Scope.Equals(other.Scope))
					 ) &&
					 (
						  NewNetwork == other.NewNetwork ||
						  (NewNetwork != null &&
						  NewNetwork.Equals(other.NewNetwork))
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (WifiMacs != null)
				{
					hash = (hash * 59) + WifiMacs.GetHashCode();
				}

				if (Ids != null)
				{
					hash = (hash * 59) + Ids.GetHashCode();
				}

				if (Serials != null)
				{
					hash = (hash * 59) + Serials.GetHashCode();
				}

				if (Scope != null)
				{
					hash = (hash * 59) + Scope.GetHashCode();
				}

				if (NewNetwork != null)
				{
					hash = (hash * 59) + NewNetwork.GetHashCode();
				}

				return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
