/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// Quality and resolution for MV21/MV71 camera models.
	/// </summary>
	[DataContract]
    public partial class MV21MV71 :  IEquatable<MV21MV71>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MV21MV71" /> class.
        /// </summary>
        [JsonConstructor]
        protected MV21MV71() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MV21MV71" /> class.
        /// </summary>
        /// <param name="Quality">Quality (required).</param>
        /// <param name="Resolution">Resolution of the camera. Can be one of &#39;1280x720&#39;. (required) (default to &quot;1280x720&quot;).</param>
        public MV21MV71(Quality1 Quality = default, string Resolution = "1280x720")
        {
            // to ensure "Quality" is required (not null)
            if (Quality == null)
            {
                throw new InvalidDataException("Quality is a required property for MV21MV71 and cannot be null");
            }
            else
            {
                this.Quality = Quality;
            }
            // to ensure "Resolution" is required (not null)
            if (Resolution == null)
            {
                throw new InvalidDataException("Resolution is a required property for MV21MV71 and cannot be null");
            }
            else
            {
                this.Resolution = Resolution;
            }
        }

        /// <summary>
        /// Gets or Sets Quality
        /// </summary>
        [DataMember(Name="quality", EmitDefaultValue=false)]
        public Quality1 Quality { get; set; }
        /// <summary>
        /// Resolution of the camera. Can be one of &#39;1280x720&#39;.
        /// </summary>
        /// <value>Resolution of the camera. Can be one of &#39;1280x720&#39;.</value>
        [DataMember(Name="resolution", EmitDefaultValue=false)]
        public string Resolution { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MV21MV71 {\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  Resolution: ").Append(Resolution).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as MV21MV71);
        }

        /// <summary>
        /// Returns true if MV21MV71 instances are equal
        /// </summary>
        /// <param name="other">Instance of MV21MV71 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MV21MV71 other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  Quality == other.Quality ||
						  (Quality != null &&
						  Quality.Equals(other.Quality))
					 ) &&
					 (
						  Resolution == other.Resolution ||
						  (Resolution != null &&
						  Resolution.Equals(other.Resolution))
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Quality != null)
				{
					hash = (hash * 59) + Quality.GetHashCode();
				}

				if (Resolution != null)
				{
					hash = (hash * 59) + Resolution.GetHashCode();
				}

				return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
