/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Meraki.Api.Data
{
	/// <summary>
	/// The privilege of the dashboard administrator on the organization. Can be one of 'full', 'read-only', 'enterprise' or 'none'
	/// </summary>
	/// <value>The privilege of the dashboard administrator on the organization. Can be one of 'full', 'read-only', 'enterprise' or 'none'</value>
	[JsonConverter(typeof(StringEnumConverter))]
    public enum OrgAccess
    {

        /// <summary>
        /// Enum Full for "full"
        /// </summary>
        [EnumMember(Value = "full")]
        Full,

        /// <summary>
        /// Enum Readonly for "read-only"
        /// </summary>
        [EnumMember(Value = "read-only")]
        Readonly,

        /// <summary>
        /// Enum Enterprise for "enterprise"
        /// </summary>
        [EnumMember(Value = "enterprise")]
        Enterprise,

        /// <summary>
        /// Enum None for "none"
        /// </summary>
        [EnumMember(Value = "none")]
        None
    }
}
