/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Meraki.Api.Data
{
	/// <summary>
	/// This policy determines how authentication requests should be handled in the event that all of the configured RADIUS servers are unreachable ('Deny access' or 'Allow access')
	/// </summary>
	/// <value>This policy determines how authentication requests should be handled in the event that all of the configured RADIUS servers are unreachable ('Deny access' or 'Allow access')</value>
	[JsonConverter(typeof(StringEnumConverter))]
    public enum RadiusFailoverPolicy
    {

        /// <summary>
        /// Enum Denyaccess for "Deny access"
        /// </summary>
        [EnumMember(Value = "Deny access")]
        Denyaccess,

        /// <summary>
        /// Enum Allowaccess for "Allow access"
        /// </summary>
        [EnumMember(Value = "Allow access")]
        Allowaccess
    }
}
