/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// Rule8
	/// </summary>
	[DataContract]
    public partial class Rule8 :  IEquatable<Rule8>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rule8" /> class.
        /// </summary>
        [JsonConstructor]
        protected Rule8() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Rule8" /> class.
        /// </summary>
        /// <param name="Name">A descriptive name for the rule.</param>
        /// <param name="PublicIp">The IP address that will be used to access the internal resource from the WAN.</param>
        /// <param name="LanIp">The IP address of the server or device that hosts the internal resource that you wish to make available on the WAN (required).</param>
        /// <param name="Uplink">Uplink.</param>
        /// <param name="AllowedInbound">The ports this mapping will provide access on, and the remote IPs that will be allowed access to the resource.</param>
        public Rule8(string Name = default, string PublicIp = default, string LanIp = default, Uplink1 Uplink = default, List<AllowedInbound> AllowedInbound = default)
        {
            // to ensure "LanIp" is required (not null)
            if (LanIp == null)
            {
                throw new InvalidDataException("LanIp is a required property for Rule8 and cannot be null");
            }
            else
            {
                this.LanIp = LanIp;
            }
            this.Name = Name;
            this.PublicIp = PublicIp;
            this.Uplink = Uplink;
            this.AllowedInbound = AllowedInbound;
        }

        /// <summary>
        /// A descriptive name for the rule
        /// </summary>
        /// <value>A descriptive name for the rule</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// The IP address that will be used to access the internal resource from the WAN
        /// </summary>
        /// <value>The IP address that will be used to access the internal resource from the WAN</value>
        [DataMember(Name="publicIp", EmitDefaultValue=false)]
        public string PublicIp { get; set; }
        /// <summary>
        /// The IP address of the server or device that hosts the internal resource that you wish to make available on the WAN
        /// </summary>
        /// <value>The IP address of the server or device that hosts the internal resource that you wish to make available on the WAN</value>
        [DataMember(Name="lanIp", EmitDefaultValue=false)]
        public string LanIp { get; set; }
        /// <summary>
        /// Gets or Sets Uplink
        /// </summary>
        [DataMember(Name="uplink", EmitDefaultValue=false)]
        public Uplink1 Uplink { get; set; }
        /// <summary>
        /// The ports this mapping will provide access on, and the remote IPs that will be allowed access to the resource
        /// </summary>
        /// <value>The ports this mapping will provide access on, and the remote IPs that will be allowed access to the resource</value>
        [DataMember(Name="allowedInbound", EmitDefaultValue=false)]
        public List<AllowedInbound> AllowedInbound { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Rule8 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PublicIp: ").Append(PublicIp).Append("\n");
            sb.Append("  LanIp: ").Append(LanIp).Append("\n");
            sb.Append("  Uplink: ").Append(Uplink).Append("\n");
            sb.Append("  AllowedInbound: ").Append(AllowedInbound).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as Rule8);
        }

        /// <summary>
        /// Returns true if Rule8 instances are equal
        /// </summary>
        /// <param name="other">Instance of Rule8 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Rule8 other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  Name == other.Name ||
						  (Name != null &&
						  Name.Equals(other.Name))
					 ) &&
					 (
						  PublicIp == other.PublicIp ||
						  (PublicIp != null &&
						  PublicIp.Equals(other.PublicIp))
					 ) &&
					 (
						  LanIp == other.LanIp ||
						  (LanIp != null &&
						  LanIp.Equals(other.LanIp))
					 ) &&
					 (
						  Uplink == other.Uplink ||
						  (Uplink != null &&
						  Uplink.Equals(other.Uplink))
					 ) &&
					 (
						  AllowedInbound == other.AllowedInbound ||
						  (AllowedInbound != null &&
						  AllowedInbound.SequenceEqual(other.AllowedInbound))
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Name != null)
				{
					hash = (hash * 59) + Name.GetHashCode();
				}

				if (PublicIp != null)
				{
					hash = (hash * 59) + PublicIp.GetHashCode();
				}

				if (LanIp != null)
				{
					hash = (hash * 59) + LanIp.GetHashCode();
				}

				if (Uplink != null)
				{
					hash = (hash * 59) + Uplink.GetHashCode();
				}

				if (AllowedInbound != null)
				{
					hash = (hash * 59) + AllowedInbound.GetHashCode();
				}

				return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
