/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// SwitchProfilePort
	/// </summary>
	[DataContract]
    public partial class SwitchProfilePort :  IEquatable<SwitchProfilePort>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SwitchProfilePort" /> class.
        /// </summary>
        [JsonConstructor]
        protected SwitchProfilePort() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SwitchProfilePort" /> class.
        /// </summary>
        /// <param name="Profile">Profile identifier. (required).</param>
        /// <param name="PortId">Port identifier of switch port. For modules, the identifier is \&quot;SlotNumber_ModuleType_PortNumber\&quot; (Ex: “1_8X10G_1”), otherwise it is just the port number (Ex: \&quot;8\&quot;). (required).</param>
        public SwitchProfilePort(string Profile = default, string PortId = default)
        {
            // to ensure "Profile" is required (not null)
            if (Profile == null)
            {
                throw new InvalidDataException("Profile is a required property for SwitchProfilePort and cannot be null");
            }
            else
            {
                this.Profile = Profile;
            }
            // to ensure "PortId" is required (not null)
            if (PortId == null)
            {
                throw new InvalidDataException("PortId is a required property for SwitchProfilePort and cannot be null");
            }
            else
            {
                this.PortId = PortId;
            }
        }

        /// <summary>
        /// Profile identifier.
        /// </summary>
        /// <value>Profile identifier.</value>
        [DataMember(Name="profile", EmitDefaultValue=false)]
        public string Profile { get; set; }
        /// <summary>
        /// Port identifier of switch port. For modules, the identifier is \&quot;SlotNumber_ModuleType_PortNumber\&quot; (Ex: “1_8X10G_1”), otherwise it is just the port number (Ex: \&quot;8\&quot;).
        /// </summary>
        /// <value>Port identifier of switch port. For modules, the identifier is \&quot;SlotNumber_ModuleType_PortNumber\&quot; (Ex: “1_8X10G_1”), otherwise it is just the port number (Ex: \&quot;8\&quot;).</value>
        [DataMember(Name="portId", EmitDefaultValue=false)]
        public string PortId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SwitchProfilePort {\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("  PortId: ").Append(PortId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as SwitchProfilePort);
        }

        /// <summary>
        /// Returns true if SwitchProfilePort instances are equal
        /// </summary>
        /// <param name="other">Instance of SwitchProfilePort to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SwitchProfilePort other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  Profile == other.Profile ||
						  Profile != null &&
						  Profile.Equals(other.Profile)
					 ) &&
					 (
						  PortId == other.PortId ||
						  PortId != null &&
						  PortId.Equals(other.PortId)
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Profile != null)
                    hash = hash * 59 + Profile.GetHashCode();
                if (PortId != null)
                    hash = hash * 59 + PortId.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
