/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// UpdateDeviceCellularGatewaySettings
	/// </summary>
	[DataContract]
    public partial class UpdateDeviceCellularGatewaySettings :  IEquatable<UpdateDeviceCellularGatewaySettings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateDeviceCellularGatewaySettings" /> class.
        /// </summary>
        /// <param name="ReservedIpRanges">list of all reserved IP ranges for a single MG.</param>
        /// <param name="FixedIpAssignments">list of all fixed IP assignments for a single MG.</param>
        public UpdateDeviceCellularGatewaySettings(List<ReservedIpRange> ReservedIpRanges = default, List<FixedIpAssignment> FixedIpAssignments = default)
        {
            this.ReservedIpRanges = ReservedIpRanges;
            this.FixedIpAssignments = FixedIpAssignments;
        }

        /// <summary>
        /// list of all reserved IP ranges for a single MG
        /// </summary>
        /// <value>list of all reserved IP ranges for a single MG</value>
        [DataMember(Name="reservedIpRanges", EmitDefaultValue=false)]
        public List<ReservedIpRange> ReservedIpRanges { get; set; }
        /// <summary>
        /// list of all fixed IP assignments for a single MG
        /// </summary>
        /// <value>list of all fixed IP assignments for a single MG</value>
        [DataMember(Name="fixedIpAssignments", EmitDefaultValue=false)]
        public List<FixedIpAssignment> FixedIpAssignments { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateDeviceCellularGatewaySettings {\n");
            sb.Append("  ReservedIpRanges: ").Append(ReservedIpRanges).Append("\n");
            sb.Append("  FixedIpAssignments: ").Append(FixedIpAssignments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as UpdateDeviceCellularGatewaySettings);
        }

        /// <summary>
        /// Returns true if UpdateDeviceCellularGatewaySettings instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateDeviceCellularGatewaySettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateDeviceCellularGatewaySettings other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  ReservedIpRanges == other.ReservedIpRanges ||
						  ReservedIpRanges != null &&
						  ReservedIpRanges.SequenceEqual(other.ReservedIpRanges)
					 ) &&
					 (
						  FixedIpAssignments == other.FixedIpAssignments ||
						  FixedIpAssignments != null &&
						  FixedIpAssignments.SequenceEqual(other.FixedIpAssignments)
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (ReservedIpRanges != null)
                    hash = hash * 59 + ReservedIpRanges.GetHashCode();
                if (FixedIpAssignments != null)
                    hash = hash * 59 + FixedIpAssignments.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
