/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// UpdateNetworkOneToManyNatRules
	/// </summary>
	[DataContract]
    public partial class UpdateNetworkOneToManyNatRules :  IEquatable<UpdateNetworkOneToManyNatRules>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNetworkOneToManyNatRules" /> class.
        /// </summary>
        [JsonConstructor]
        protected UpdateNetworkOneToManyNatRules() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNetworkOneToManyNatRules" /> class.
        /// </summary>
        /// <param name="Rules">An array of 1:Many nat rules (required).</param>
        public UpdateNetworkOneToManyNatRules(List<Rule7> Rules = default)
        {
            // to ensure "Rules" is required (not null)
            if (Rules == null)
            {
                throw new InvalidDataException("Rules is a required property for UpdateNetworkOneToManyNatRules and cannot be null");
            }
            else
            {
                this.Rules = Rules;
            }
        }

        /// <summary>
        /// An array of 1:Many nat rules
        /// </summary>
        /// <value>An array of 1:Many nat rules</value>
        [DataMember(Name="rules", EmitDefaultValue=false)]
        public List<Rule7> Rules { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateNetworkOneToManyNatRules {\n");
            sb.Append("  Rules: ").Append(Rules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as UpdateNetworkOneToManyNatRules);
        }

        /// <summary>
        /// Returns true if UpdateNetworkOneToManyNatRules instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateNetworkOneToManyNatRules to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateNetworkOneToManyNatRules other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: Rules == other.Rules ||
						  (Rules != null &&
						  Rules.SequenceEqual(other.Rules));
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Rules != null)
				{
					hash = (hash * 59) + Rules.GetHashCode();
				}

				return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
