/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// UpdateNetworkFirewalledService
	/// </summary>
	[DataContract]
    public partial class UpdateNetworkFirewalledService :  IEquatable<UpdateNetworkFirewalledService>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNetworkFirewalledService" /> class.
        /// </summary>
        [JsonConstructor]
        protected UpdateNetworkFirewalledService() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNetworkFirewalledService" /> class.
        /// </summary>
        /// <param name="Access">Access (required).</param>
        /// <param name="AllowedIps">An array of whitelisted IPs that can access the service. This field is required if \&quot;access\&quot; is set to \&quot;restricted\&quot;. Otherwise this field is ignored.</param>
        public UpdateNetworkFirewalledService(Access Access = default, List<string> AllowedIps = default)
        {
            // to ensure "Access" is required (not null)
            if (Access == null)
            {
                throw new InvalidDataException("Access is a required property for UpdateNetworkFirewalledService and cannot be null");
            }
            else
            {
                this.Access = Access;
            }
            this.AllowedIps = AllowedIps;
        }

        /// <summary>
        /// Gets or Sets Access
        /// </summary>
        [DataMember(Name="access", EmitDefaultValue=false)]
        public Access Access { get; set; }
        /// <summary>
        /// An array of whitelisted IPs that can access the service. This field is required if \&quot;access\&quot; is set to \&quot;restricted\&quot;. Otherwise this field is ignored
        /// </summary>
        /// <value>An array of whitelisted IPs that can access the service. This field is required if \&quot;access\&quot; is set to \&quot;restricted\&quot;. Otherwise this field is ignored</value>
        [DataMember(Name="allowedIps", EmitDefaultValue=false)]
        public List<string> AllowedIps { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateNetworkFirewalledService {\n");
            sb.Append("  Access: ").Append(Access).Append("\n");
            sb.Append("  AllowedIps: ").Append(AllowedIps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as UpdateNetworkFirewalledService);
        }

        /// <summary>
        /// Returns true if UpdateNetworkFirewalledService instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateNetworkFirewalledService to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateNetworkFirewalledService other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  Access == other.Access ||
						  Access != null &&
						  Access.Equals(other.Access)
					 ) &&
					 (
						  AllowedIps == other.AllowedIps ||
						  AllowedIps != null &&
						  AllowedIps.SequenceEqual(other.AllowedIps)
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Access != null)
                    hash = hash * 59 + Access.GetHashCode();
                if (AllowedIps != null)
                    hash = hash * 59 + AllowedIps.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
