/*
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * OpenAPI spec version: 0.10.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Meraki.Api.Data
{
	/// <summary>
	/// UpdateNetworkWirelessSettings
	/// </summary>
	[DataContract]
	public partial class WirelessSettingsUpdateDto
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="WirelessSettingsUpdateDto" /> class.
		/// </summary>
		/// <param name="MeshingEnabled">Toggle for enabling or disabling meshing in a network.</param>
		/// <param name="Ipv6BridgeEnabled">Toggle for enabling or disabling IPv6 bridging in a network (Note: if enabled, SSIDs must also be configured to use bridge mode).</param>
		/// <param name="LocationAnalyticsEnabled">Toggle for enabling or disabling location analytics for your network.</param>
		/// <param name="LedLightsOn">Toggle for enabling or disabling LED lights on all APs in the network (making them run dark).</param>
		public WirelessSettingsUpdateDto(bool? MeshingEnabled = default, bool? Ipv6BridgeEnabled = default, bool? LocationAnalyticsEnabled = default, bool? LedLightsOn = default)
		{
			this.MeshingEnabled = MeshingEnabled;
			this.Ipv6BridgeEnabled = Ipv6BridgeEnabled;
			this.LocationAnalyticsEnabled = LocationAnalyticsEnabled;
			this.LedLightsOn = LedLightsOn;
		}

		/// <summary>
		/// Toggle for enabling or disabling meshing in a network
		/// </summary>
		/// <value>Toggle for enabling or disabling meshing in a network</value>
		[DataMember(Name = "meshingEnabled", EmitDefaultValue = false)]
		public bool? MeshingEnabled { get; set; }
		/// <summary>
		/// Toggle for enabling or disabling IPv6 bridging in a network (Note: if enabled, SSIDs must also be configured to use bridge mode)
		/// </summary>
		/// <value>Toggle for enabling or disabling IPv6 bridging in a network (Note: if enabled, SSIDs must also be configured to use bridge mode)</value>
		[DataMember(Name = "ipv6BridgeEnabled", EmitDefaultValue = false)]
		public bool? Ipv6BridgeEnabled { get; set; }
		/// <summary>
		/// Toggle for enabling or disabling location analytics for your network
		/// </summary>
		/// <value>Toggle for enabling or disabling location analytics for your network</value>
		[DataMember(Name = "locationAnalyticsEnabled", EmitDefaultValue = false)]
		public bool? LocationAnalyticsEnabled { get; set; }
		/// <summary>
		/// Toggle for enabling or disabling LED lights on all APs in the network (making them run dark)
		/// </summary>
		/// <value>Toggle for enabling or disabling LED lights on all APs in the network (making them run dark)</value>
		[DataMember(Name = "ledLightsOn", EmitDefaultValue = false)]
		public bool? LedLightsOn { get; set; }
	}
}
