/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// UpdateNetworkContentFiltering
	/// </summary>
	[DataContract]
    public partial class UpdateNetworkContentFiltering :  IEquatable<UpdateNetworkContentFiltering>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNetworkContentFiltering" /> class.
        /// </summary>
        /// <param name="AllowedUrlPatterns">A whitelist of URL patterns to allow.</param>
        /// <param name="BlockedUrlPatterns">A blacklist of URL patterns to block.</param>
        /// <param name="BlockedUrlCategories">A list of URL categories to block.</param>
        /// <param name="UrlCategoryListSize">UrlCategoryListSize.</param>
        public UpdateNetworkContentFiltering(List<string> AllowedUrlPatterns = default, List<string> BlockedUrlPatterns = default, List<string> BlockedUrlCategories = default, UrlCategoryListSize UrlCategoryListSize = default)
        {
            this.AllowedUrlPatterns = AllowedUrlPatterns;
            this.BlockedUrlPatterns = BlockedUrlPatterns;
            this.BlockedUrlCategories = BlockedUrlCategories;
            this.UrlCategoryListSize = UrlCategoryListSize;
        }

        /// <summary>
        /// A whitelist of URL patterns to allow
        /// </summary>
        /// <value>A whitelist of URL patterns to allow</value>
        [DataMember(Name="allowedUrlPatterns", EmitDefaultValue=false)]
        public List<string> AllowedUrlPatterns { get; set; }
        /// <summary>
        /// A blacklist of URL patterns to block
        /// </summary>
        /// <value>A blacklist of URL patterns to block</value>
        [DataMember(Name="blockedUrlPatterns", EmitDefaultValue=false)]
        public List<string> BlockedUrlPatterns { get; set; }
        /// <summary>
        /// A list of URL categories to block
        /// </summary>
        /// <value>A list of URL categories to block</value>
        [DataMember(Name="blockedUrlCategories", EmitDefaultValue=false)]
        public List<string> BlockedUrlCategories { get; set; }
        /// <summary>
        /// Gets or Sets UrlCategoryListSize
        /// </summary>
        [DataMember(Name="urlCategoryListSize", EmitDefaultValue=false)]
        public UrlCategoryListSize UrlCategoryListSize { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateNetworkContentFiltering {\n");
            sb.Append("  AllowedUrlPatterns: ").Append(AllowedUrlPatterns).Append("\n");
            sb.Append("  BlockedUrlPatterns: ").Append(BlockedUrlPatterns).Append("\n");
            sb.Append("  BlockedUrlCategories: ").Append(BlockedUrlCategories).Append("\n");
            sb.Append("  UrlCategoryListSize: ").Append(UrlCategoryListSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as UpdateNetworkContentFiltering);
        }

        /// <summary>
        /// Returns true if UpdateNetworkContentFiltering instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateNetworkContentFiltering to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateNetworkContentFiltering other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  AllowedUrlPatterns == other.AllowedUrlPatterns ||
						  AllowedUrlPatterns != null &&
						  AllowedUrlPatterns.SequenceEqual(other.AllowedUrlPatterns)
					 ) &&
					 (
						  BlockedUrlPatterns == other.BlockedUrlPatterns ||
						  BlockedUrlPatterns != null &&
						  BlockedUrlPatterns.SequenceEqual(other.BlockedUrlPatterns)
					 ) &&
					 (
						  BlockedUrlCategories == other.BlockedUrlCategories ||
						  BlockedUrlCategories != null &&
						  BlockedUrlCategories.SequenceEqual(other.BlockedUrlCategories)
					 ) &&
					 (
						  UrlCategoryListSize == other.UrlCategoryListSize ||
						  UrlCategoryListSize != null &&
						  UrlCategoryListSize.Equals(other.UrlCategoryListSize)
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (AllowedUrlPatterns != null)
                    hash = hash * 59 + AllowedUrlPatterns.GetHashCode();
                if (BlockedUrlPatterns != null)
                    hash = hash * 59 + BlockedUrlPatterns.GetHashCode();
                if (BlockedUrlCategories != null)
                    hash = hash * 59 + BlockedUrlCategories.GetHashCode();
                if (UrlCategoryListSize != null)
                    hash = hash * 59 + UrlCategoryListSize.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
