/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// UpdateNetworkSwitchSettingsMulticast
	/// </summary>
	[DataContract]
    public partial class UpdateNetworkSwitchSettingsMulticast :  IEquatable<UpdateNetworkSwitchSettingsMulticast>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNetworkSwitchSettingsMulticast" /> class.
        /// </summary>
        /// <param name="DefaultSettings">DefaultSettings.</param>
        /// <param name="Overrides">Array of paired switches/stacks/profiles and corresponding multicast settings. An empty array will clear the multicast settings..</param>
        public UpdateNetworkSwitchSettingsMulticast(DefaultSettings DefaultSettings = default, List<Override1> Overrides = default)
        {
            this.DefaultSettings = DefaultSettings;
            this.Overrides = Overrides;
        }

        /// <summary>
        /// Gets or Sets DefaultSettings
        /// </summary>
        [DataMember(Name="defaultSettings", EmitDefaultValue=false)]
        public DefaultSettings DefaultSettings { get; set; }
        /// <summary>
        /// Array of paired switches/stacks/profiles and corresponding multicast settings. An empty array will clear the multicast settings.
        /// </summary>
        /// <value>Array of paired switches/stacks/profiles and corresponding multicast settings. An empty array will clear the multicast settings.</value>
        [DataMember(Name="overrides", EmitDefaultValue=false)]
        public List<Override1> Overrides { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateNetworkSwitchSettingsMulticast {\n");
            sb.Append("  DefaultSettings: ").Append(DefaultSettings).Append("\n");
            sb.Append("  Overrides: ").Append(Overrides).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as UpdateNetworkSwitchSettingsMulticast);
        }

        /// <summary>
        /// Returns true if UpdateNetworkSwitchSettingsMulticast instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateNetworkSwitchSettingsMulticast to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateNetworkSwitchSettingsMulticast other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: (
						  DefaultSettings == other.DefaultSettings ||
						  (DefaultSettings != null &&
						  DefaultSettings.Equals(other.DefaultSettings))
					 ) &&
					 (
						  Overrides == other.Overrides ||
						  (Overrides != null &&
						  Overrides.SequenceEqual(other.Overrides))
					 );
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (DefaultSettings != null)
				{
					hash = (hash * 59) + DefaultSettings.GetHashCode();
				}

				if (Overrides != null)
				{
					hash = (hash * 59) + Overrides.GetHashCode();
				}

				return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
