/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;using System.Threading.Tasks;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Meraki.Api.Data
{
	/// <summary>
	/// UpdateNetworkSwitchSettingsDscpToCosMappings
	/// </summary>
	[DataContract]
    public partial class UpdateNetworkSwitchSettingsDscpToCosMappings :  IEquatable<UpdateNetworkSwitchSettingsDscpToCosMappings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNetworkSwitchSettingsDscpToCosMappings" /> class.
        /// </summary>
        [JsonConstructor]
        protected UpdateNetworkSwitchSettingsDscpToCosMappings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNetworkSwitchSettingsDscpToCosMappings" /> class.
        /// </summary>
        /// <param name="Mappings">An array of DSCP to CoS mappings. An empty array will reset the mappings to default. (required).</param>
        public UpdateNetworkSwitchSettingsDscpToCosMappings(List<Mapping> Mappings = default)
        {
            // to ensure "Mappings" is required (not null)
            if (Mappings == null)
            {
                throw new InvalidDataException("Mappings is a required property for UpdateNetworkSwitchSettingsDscpToCosMappings and cannot be null");
            }
            else
            {
                this.Mappings = Mappings;
            }
        }

        /// <summary>
        /// An array of DSCP to CoS mappings. An empty array will reset the mappings to default.
        /// </summary>
        /// <value>An array of DSCP to CoS mappings. An empty array will reset the mappings to default.</value>
        [DataMember(Name="mappings", EmitDefaultValue=false)]
        public List<Mapping> Mappings { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateNetworkSwitchSettingsDscpToCosMappings {\n");
            sb.Append("  Mappings: ").Append(Mappings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as UpdateNetworkSwitchSettingsDscpToCosMappings);
        }

        /// <summary>
        /// Returns true if UpdateNetworkSwitchSettingsDscpToCosMappings instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateNetworkSwitchSettingsDscpToCosMappings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateNetworkSwitchSettingsDscpToCosMappings other)
        {
			// credit: http://stackoverflow.com/a/10454552/677735
			return other == null
					? false
					: Mappings == other.Mappings ||
						  (Mappings != null &&
						  Mappings.SequenceEqual(other.Mappings));
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Mappings != null)
				{
					hash = (hash * 59) + Mappings.GetHashCode();
				}

				return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
