/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Meraki.Api.Data
{
	/// <summary>
	/// The SNMP version 3 privacy mode. Can be either 'DES' or 'AES128'.
	/// </summary>
	/// <value>The SNMP version 3 privacy mode. Can be either 'DES' or 'AES128'.</value>
	[JsonConverter(typeof(StringEnumConverter))]
    public enum V3PrivMode
    {

        /// <summary>
        /// Enum DES for "DES"
        /// </summary>
        [EnumMember(Value = "DES")]
        DES,

        /// <summary>
        /// Enum AES128 for "AES128"
        /// </summary>
        [EnumMember(Value = "AES128")]
        AES128
    }
}
