/* 
 * Meraki Dashboard API
 *
 *   *Version 0.10.0*  The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 01 April, 2020 > > [What's New](https://meraki.io/whats-new/)  - --  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)     
 *
 * OpenAPI spec version: 0.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Meraki.Api.Data
{
	/// <summary>
	/// The types of WPA encryption. ('WPA1 only', 'WPA1 and WPA2', 'WPA2 only', 'WPA3 Transition Mode' or 'WPA3 only')
	/// </summary>
	/// <value>The types of WPA encryption. ('WPA1 only', 'WPA1 and WPA2', 'WPA2 only', 'WPA3 Transition Mode' or 'WPA3 only')</value>
	[JsonConverter(typeof(StringEnumConverter))]
    public enum WpaEncryptionMode
    {

        /// <summary>
        /// Enum WPA1only for "WPA1 only"
        /// </summary>
        [EnumMember(Value = "WPA1 only")]
        WPA1only,

        /// <summary>
        /// Enum WPA1andWPA2 for "WPA1 and WPA2"
        /// </summary>
        [EnumMember(Value = "WPA1 and WPA2")]
        WPA1andWPA2,

        /// <summary>
        /// Enum WPA2only for "WPA2 only"
        /// </summary>
        [EnumMember(Value = "WPA2 only")]
        WPA2only,

        /// <summary>
        /// Enum WPA3TransitionMode for "WPA3 Transition Mode"
        /// </summary>
        [EnumMember(Value = "WPA3 Transition Mode")]
        WPA3TransitionMode,

        /// <summary>
        /// Enum WPA3only for "WPA3 only"
        /// </summary>
        [EnumMember(Value = "WPA3 only")]
        WPA3only
    }
}
